TheBillboard/Models/Author.cs
using Microsoft.AspNetCore.Mvc;

namespace TheBillboard.MVC.Models
{
    public record Author
    {
        public Author(
            int? id = default,
            string name = "",
            string surname = "")
        {
            Name = name;
            Surname = surname;
            Id = id;
        }
        public string Name { get; init; }
        public string Surname { get; init; }
        public int? Id { get; init; }

        public override string ToString() => Name + " " + Surname;
    }
}

TheBillboard/Models/ErrorViewModel.cs
namespace TheBillboard.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TheBillboard/Models/Message.cs
using System.ComponentModel.DataAnnotations;

namespace TheBillboard.MVC.Models;
public record Message
{
    public Message(
        string title = "",
        [Required(ErrorMessage = "Il campo Message e' obbligatorio")] [MinLength(5, ErrorMessage = "Il campo Message deve essere lungo almento 5 caratteri")]
        string body = "",
        int authorId = default,
        Author? author = default,
        DateTime? createdAt = default,
        DateTime? updatedAt = default,
        int? id = default)
    {
        Title = title;
        Body = body;
        AuthorId = authorId;
        Author = author;
        CreatedAt = createdAt;
        UpdatedAt = updatedAt;
        Id = id;
    }    
    public Message(
        int id,
        string title,
        string body,
        DateTime CreatedAt,
        DateTime UpdatedAt,
        int authorId,
        string name,
        string surname)
    {
        Id = id;
        Title = title;
        Body = body;
        AuthorId = authorId;
        this.CreatedAt = CreatedAt;
        this.UpdatedAt = UpdatedAt;
        Author = new Author(authorId, name, surname);
    }

    public string Title { get; init; }
    public string Body { get; init; }
    public int AuthorId { get; init; }
    public Author? Author { get; init; }
    public DateTime? CreatedAt { get; init; }
    public DateTime? UpdatedAt { get; init; }
    public int? Id { get; init; }

    public string FormattedCreatedAt => CreatedAt.HasValue
        ? CreatedAt.Value.ToString("yyyy-MM-dd HH:mm")
        : string.Empty;

    public string FormattedUpdatedAt => UpdatedAt.HasValue
        ? UpdatedAt.Value.ToString("yyyy-MM-dd HH:mm")
        : string.Empty;
}

TheBillboard/Models/MessageWithAuthor.cs
namespace TheBillboard.MVC.Models
{
    public record MessageWithAuthor(Message Message, Author Author);
}

TheBillboard/ViewModels/AuthorIndexViewModel.cs
using TheBillboard.MVC.Models;

namespace TheBillboard.MVC.ViewModels
{
    public record AuthorIndexViewModel (Author Author, bool IsDeletable);    
}

TheBillboard/ViewModels/MessageCreationViewModel.cs
namespace TheBillboard.MVC.Models
{
    public record MessageCreationViewModel(Message Message, IEnumerable<Author> Authors);
}

TheBillboard/ViewModels/MessagesIndexViewModel.cs
using TheBillboard.MVC.Models;

namespace TheBillboard.MVC.ViewModels
{
    public record MessagesIndexViewModel(MessageCreationViewModel MessageCreationViewModel, IEnumerable<MessageWithAuthor> Messages);
}

TheBillboard/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using TheBillboard.MVC.Abstract;
using TheBillboard.MVC.Models;
using TheBillboard.MVC.ViewModels;

namespace TheBillboard.MVC.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorGateway _authorGateway;
        private readonly IMessageGateway _messageGateway;

        public AuthorsController(IAuthorGateway authorGateway, IMessageGateway messageGateway)
        {
            _authorGateway = authorGateway;
            _messageGateway = messageGateway;
        }

        public async Task<IActionResult> Index()
        {
            var authors = await _authorGateway.GetAllAsync();
            var messages = await _messageGateway.GetAllAsync();

            var authorIndexViewModelList = new List<AuthorIndexViewModel>();
            foreach (var author in authors)
            {
                var isDeletable = !(messages.Any(t => t.AuthorId == author.Id));
                authorIndexViewModelList.Add(new AuthorIndexViewModel(author, isDeletable));
            }

            return View(authorIndexViewModelList);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Author author)
        {
            if (!ModelState.IsValid)
                return View();            

            await _authorGateway.Create(author);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Create(int? id)
        {
            if (id is not null)
                return View(await _authorGateway.GetById((int)id)!);            

            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _authorGateway.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

TheBillboard/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TheBillboard.MVC.Abstract;
using TheBillboard.MVC.Gateways;
using TheBillboard.MVC.Models;

namespace TheBillboard.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IStudentGateway _studentGateway;
    
    public HomeController(IStudentGateway studentGateway, ILogger<HomeController> logger)
    {
        _logger = logger;
        _studentGateway = studentGateway;
    }

    public IActionResult Index() => View();
    
    public IActionResult Students() => View("Students", _studentGateway.GetStudents());

    public IActionResult About() => View();

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() => View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
}

TheBillboard/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using TheBillboard.MVC.Abstract;
using TheBillboard.MVC.Models;
using TheBillboard.MVC.ViewModels;

namespace TheBillboard.MVC.Controllers;

public class MessagesController : Controller
{
    private readonly IMessageGateway _messageGateway;
    private readonly IAuthorGateway _authorGateway;
    private readonly ILogger<MessagesController> _logger;

    public MessagesController(IMessageGateway messageGateway, ILogger<MessagesController> logger, IAuthorGateway authorGateway)
    {
        _logger = logger;
        _messageGateway = messageGateway;
        _authorGateway = authorGateway;
    }

    public async Task<IActionResult> Index()
    {
        var messages = await  _messageGateway.GetAllAsync();
        var authors = await _authorGateway.GetAllAsync();

        var messagesWithAuthor = messages.Select(message => MatchAuthorToMessage(message, authors));

        var createViewModel = new MessageCreationViewModel(new Message(), authors);
        var indexModel = new MessagesIndexViewModel(createViewModel, messagesWithAuthor);
        return View(indexModel);
    }

    [HttpGet]
    public async Task<IActionResult> Create(int? id)
    {
        var message = id is not null ? await _messageGateway.GetByIdAsync((int)id)! : new Message();

        if (message is null)
            return View("Error");
        else
        {
            var viewModel = new MessageCreationViewModel(message, await _authorGateway.GetAllAsync());
            return View(viewModel);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Create(Message message)
    {
        if (!ModelState.IsValid)
            return View(new MessageCreationViewModel(message, await _authorGateway.GetAllAsync()));

        if (message.Id == default)
            await _messageGateway.CreateAsync(message);
        else
            await _messageGateway.UpdateAsync(message);

        _logger.LogInformation($"Message received: {message.Title}");
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Detail(int id)
    {
        var message = await _messageGateway.GetByIdAsync(id)!;
        if (message is null)
            return View("Error");

        var author = await _authorGateway.GetById(message.AuthorId)!;
        return View(new MessageWithAuthor(message, author));
    }

    public async Task<IActionResult> Delete(int id)
    {
        await _messageGateway. DeleteAsync(id);
        return RedirectToAction("Index");
    }

    private MessageWithAuthor MatchAuthorToMessage(Message message, IEnumerable<Author> authors)
        => new MessageWithAuthor(message, authors.First(a => a.Id == message.AuthorId));
}

TheBillboard/Views/Authors/Create.cshtml
@model Author

@{
    ViewData["Title"] = "Create New Author";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>

    <form class="card" asp-action="Create" asp-controller="Authors" method="post">
        <div class="form-group">
            <label for="body">New Author</label>
            <input asp-for="Name" type="text" class="form-control" placeholder="Name">
            <input asp-for="Surname" type="text" class="form-control" placeholder="Surname">
        </div>
        <button type="submit" class="btn btn-sm btn-outline-primary">Create</button>
    </form>
</div>

TheBillboard/Views/Authors/Index.cshtml
@model IEnumerable<AuthorIndexViewModel>

@{
    ViewData["Title"] = "Lista di Autori";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>

    <ul class="list-group list-group-flush align-items-center">
        @foreach (var author in Model)
        {
            <li class="list-group-item">
                <div class="card">
                    <div class="d-flex flex-column card-body">
                        <h5 class="card-title">@author.Author.ToString()</h5>
                        @if(author.IsDeletable)
                        {
                        @Html.ActionLink("Remove", "Delete", new { id = author.Author.Id }, new { @class = "btn btn-sm btn-outline-danger w-25" })                            
                        }
                    </div>
                </div>
            </li>
        }        
    </ul>
    @Html.ActionLink("Create New Author", "Create", "Authors", default, new { @class = "btn btn-sm btn-outline-danger w-25" })

</div>

TheBillboard/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>wonderfull, amazing</p>

TheBillboard/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <h5 class="text-muted">You type it, we post it!</h5>

    @Html.ActionLink("Get Started", "Index", "Messages", default, new { @class = "btn btn-sm btn-outline-primary w-25" })
    <a class="btn btn-sm btn-outline-primary w-25" asp-action="About">About</a>
</div>

TheBillboard/Views/Home/Students.cshtml
@model IEnumerable<string>

@{
    ViewData["Title"] = "Students";
}

<div class="text-center">
    @if (!Model.Any())
    {
        <div>Looading ...</div>
        return;
    }


    <h1 class="display-4">@ViewData["Title"]</h1>
    <ul>
        @foreach (var student in Model)
        {
            <li>@student</li>
        }
    </ul>
</div>

TheBillboard/Views/Messages/Create.cshtml
@model MessageCreationViewModel

@{
    ViewData["Title"] = "Message creation";
}

<div class="text-center" xmlns="http://www.w3.org/1999/html">
    <h1 class="display-4">@ViewData["Title"]</h1>
    @await Html.PartialAsync("MessageCreate", Model)
</div>

TheBillboard/Views/Messages/Detail.cshtml
@model MessageWithAuthor

@{
    ViewData["Title"] = "Message detail";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <div class="card">
        <div class="d-flex flex-column card-body">
            <h5 class="card-title">@Model.Message.Title</h5>
            <h6 class="card-subtitle mb-2 text-muted">@Model.Author.ToString()</h6>
            <p class="card-text">@Model.Message.Body</p>
            @Html.ActionLink("Delete", "Delete", new { id = Model.Message.Id }, new { @class = "btn btn-sm btn-outline-danger w-25" })
            
        </div>
        <div class="d-flex flex-column align-items-end card-footer">
            <div><small class="text-muted"><strong>Created at:</strong> @Model.Message.FormattedCreatedAt</small></div>
            <div><small class="text-muted"><strong>Updated at:</strong> @Model.Message.FormattedUpdatedAt</small></div>
        </div>
    </div>
</div>

TheBillboard/Views/Messages/Index.cshtml
@model MessagesIndexViewModel

@{
    ViewData["Title"] = "Messages";
}

<div class="text-center">    
    <h3 class="display-4">Message List</h3>

    <button id="createMessageBtn" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newMessageModal" data>New message</button>
    <!-- Start modal -->
    <div class="modal fade" id="newMessageModal" tabindex="-1" aria-labelledby="newMessageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="newMessageModalLabel">New Message</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @await Html.PartialAsync("MessageCreate", Model.MessageCreationViewModel)
                </div>
            </div>
        </div>
    </div>
    <!-- End modal -->

    <ul class="list-group list-group-flush align-items-center">
        @foreach (var message in Model.Messages)
        {
            <li class="list-group-item">
                <div class="card">
                    <div class="d-flex flex-column card-body">
                        <h5 class="card-title">@message.Message.Title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@message.Author.ToString()</h6>
                        <p class="card-text">@message.Message.Body</p>
                        @Html.ActionLink("Detail", "Detail", new { id = message.Message.Id }, new { @class = "btn btn-sm btn-outline-primary w-25" })
                        @Html.ActionLink("Edit", "Create", new { id = message.Message.Id }, new { @class = "btn btn-sm btn-outline-danger w-25" })                        
                    </div>
                    <div class="d-flex flex-column align-items-end card-footer">
                        <small class="text-muted"><strong>Updated at: </strong> @message.Message.FormattedUpdatedAt</small>
                    </div>
                </div>
            </li>
        }         
    </ul>
</div>

TheBillboard/Views/Shared/MessageCreate.cshtml
@model MessageCreationViewModel

<form id="MessageCreate" class="card" asp-action="Create" asp-controller="Messages" method="post">
    <div class="form-group">
        @if (Model.Message is not null)
        {
            <input asp-for="@Model.Message.Id" type="hidden" value="@Model.Message.Id" />
        }
        <div>
            <label for="body">Title</label>
            <input asp-for="Message.Title" type="text" class="form-control" placeholder="Title">
            <span asp-validation-for="Message.Title" class="text-danger"></span>
        </div>
        <div>
            <label for="Message.AuthorId">Author</label>
            @if (Model.Message.Id is null)
            {
                <select asp-for="Message.AuthorId" class="form-select">
                    @foreach (var author in Model.Authors)
                        {
                            <option value="@author.Id">@author.ToString()</option>
                        }                    
                </select>
            }
            else
            {
                <div class="form-control"><label>@Model.Message.Author!.ToString()</label>   </div>
                <input asp-for="Message.AuthorId" hidden="true" type="text" class="form-control" value="@Model.Message.AuthorId">
            }
        </div>
        <div>
            <label for="body">Message</label>
            <textarea asp-for="Message.Body" type="text" class="form-control" placeholder="Enter message"></textarea>
            <span asp-validation-for="Message.Body" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-sm btn-outline-primary">Send</button>
</form>

TheBillboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TheBillboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TheBillboard.MVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TheBillboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Messages" asp-action="Index">Messages</a>
                    </li>      
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Authors" asp-action="Index">Author</a>
                    </li>      
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Students">Students</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - TheBillboard - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>